[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "connect4"
version = "1.0"
requires-python = ">=3.11"
dependencies = ["numpy"]

[project.optional-dependencies]
dev = ["pytest", "black", "mypy"]

