from connect4 import State, Player

board = State()

print(board.turn(Player.Blue, 2))
board.display()
print(board.turn(Player.Red, 3))
board.display()
print(board.turn(Player.Blue, 1))
board.display()
print(board.turn(Player.Red, 2))
board.display()
print(board.turn(Player.Blue, 0))
board.display()
print(board.turn(Player.Red, 0))
board.display()
print(board.turn(Player.Blue, 1))
board.display()
print(board.turn(Player.Red, 1))
board.display()
print(board.turn(Player.Blue, 0))
board.display()
print(board.turn(Player.Red, 0))
board.display()
